[sdl]
output = texturenb
fullscreen = off
window_size = 1280x700
window_decorations = on

[render]
aspect = auto

[cpu]
core = auto
cputype = auto
cpu_cycles = 3000

[autoexec]
mount c "."
c:
QBASIC.EXE /RUN GORILLA.BAS
